Repository friendlyantz/who_is_america, pull requests merged in 2021-02, with the labels that each got.

#4 ARCH: Location self-referencing setup
  app/models/location.rb
  app/models/politician.rb
  db/migrate/20210202204457_create_locations.rb
  db/schema.rb
  test/fixtures/locations.yml
  test/models/location_test.rb
Labels: enhancement

#5 ARCH: politicians controller added and table updated
  app/assets/stylesheets/politicians.scss
  app/controllers/pages_controller.rb
  app/controllers/politicians_controller.rb
  app/helpers/politicians_helper.rb
  app/views/pages/home.html.erb
  app/views/politicians/index.html.erb
  app/views/politicians/show.html.erb
  app/views/shared/_navbar.html.erb
  config/routes.rb
  db/migrate/20210204231523_add_party_to_politicians.rb
  db/migrate/20210204231809_add_location_to_politicians.rb
  db/schema.rb
  test/controllers/politicians_controller_test.rb
Labels: ARCH

#8 source tracker migration
  app/models/quote.rb
  app/models/source_tracker.rb
  db/migrate/20210211205346_create_source_trackers.rb
  db/migrate/20210211211409_add_source_tracker_to_quotes.rb
  db/schema.rb
  test/fixtures/source_trackers.yml
  test/models/source_tracker_test.rb
Labels: ARCH

#9 ARCH: vote model generation and user+quote associations
  .gitignore
  app/controllers/politicians_controller.rb
  app/models/quote.rb
  app/models/user.rb
  app/models/vote.rb
  app/views/pages/home.html.erb
  app/views/politicians/index.html.erb
  db/migrate/20210211221720_create_votes.rb
  db/schema.rb
  db/seeds.rb
  test/fixtures/votes.yml
  test/models/vote_test.rb
Labels: ARCH

#10 ARCH: UserTracker model and migration. match_ration
  app/models/politician.rb
  app/models/user.rb
  app/models/user_tracker.rb
  db/migrate/20210217212008_create_user_trackers.rb
  db/schema.rb
  db/seeds.rb
  test/fixtures/user_trackers.yml
  test/models/user_tracker_test.rb
Labels: ARCH

#11 TDD: Rspec setup, and user test
  .rspec
  Gemfile
  Gemfile.lock
  spec/models/user_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: TDD

#13 welcome page setup and authentification routing
  app/controllers/pages_controller.rb
  app/controllers/politicians_controller.rb
  app/views/pages/home.html.erb
  app/views/pages/welcome.html.erb
  app/views/politicians/index.html.erb
  app/views/politicians/show.html.erb
  app/views/shared/_navbar.html.erb
  config/routes.rb
Labels: ARCH

#14 dashboard/my acc, contribute and quotes MCV
  app/assets/stylesheets/quotes.scss
  app/controllers/pages_controller.rb
  app/controllers/quotes_controller.rb
  app/helpers/quotes_helper.rb
  app/models/quote.rb
  app/views/pages/contribute.html.erb
  app/views/pages/my_account.html.erb
  app/views/quotes/index.html.erb
  app/views/shared/_navbar.html.erb
  config/routes.rb
  spec/helpers/quotes_helper_spec.rb
  spec/requests/quotes_request_spec.rb
  spec/views/quotes/index.html.erb_spec.rb
Labels: ARCH

#15 Added quiz page with random not voted quote
  app/controllers/pages_controller.rb
  app/models/vote.rb
  app/views/pages/quiz.html.erb
  app/views/shared/_navbar.html.erb
  config/routes.rb
Labels: ARCH, FEAT
