Repository friendlyantz/who_is_america, pull requests merged in 2021-03, with the labels that each got.

#16 Mvc controllers
  app/controllers/quotes_controller.rb
  app/views/pages/contribute.html.erb
  app/views/pages/quiz.html.erb
  app/views/quotes/edit.html.erb
  app/views/quotes/index.html.erb
  app/views/quotes/new.html.erb
  app/views/shared/_navbar.html.erb
  config/routes.rb
  db/schema.rb
  db/seeds.rb
Labels: ARCH

#17 Ap
  Gemfile
  Gemfile.lock
Labels: ARCH

#23 Quiz refined
  app/assets/stylesheets/votes.scss
  app/controllers/pages_controller.rb
  app/controllers/votes_controller.rb
  app/helpers/votes_helper.rb
  app/models/user.rb
  app/models/vote.rb
  app/views/pages/quiz.html.erb
  app/views/votes/new.html.erb
  config/routes.rb
  db/migrate/20210302204828_add_permissions_to_users.rb
  db/schema.rb
  db/seeds.rb
  spec/helpers/votes_helper_spec.rb
  spec/requests/votes_request_spec.rb
Labels: FEAT

#25 Politician - MVC new/edit
  app/controllers/politicians_controller.rb
  app/controllers/quotes_controller.rb
  app/views/pages/contribute.html.erb
  app/views/politicians/edit.erb
  app/views/politicians/new.html.erb
  app/views/politicians/show.html.erb
  config/routes.rb
  spec/requests/politicians_request_spec.rb
Labels: ARCH

#26 Add dotenv - Protect my secret data in .env filegs+cloudinary gem
  .gitignore
  Gemfile
  Gemfile.lock
  app/controllers/politicians_controller.rb
  app/models/politician.rb
  app/views/pages/home.html.erb
  app/views/politicians/edit.erb
  app/views/politicians/new.html.erb
  app/views/politicians/show.html.erb
  config/environments/development.rb
  config/storage.yml
  db/migrate/20210309200724_create_active_storage_tables.active_storage.rb
  db/schema.rb
Labels: ARCH

#33 FEAT: Pundid squashed without env
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/politicians_controller.rb
  app/controllers/quotes_controller.rb
  app/policies/application_policy.rb
  app/policies/politician_policy.rb
  app/policies/quote_policy.rb
  app/views/layouts/application.html.erb
  app/views/pages/contribute.html.erb
  app/views/politicians/index.html.erb
  app/views/politicians/show.html.erb
  app/views/quotes/edit.html.erb
  app/views/quotes/index.html.erb
  app/views/quotes/new.html.erb
  config/routes.rb
  spec/policies/politician_policy_spec.rb
  spec/policies/quote_policy_spec.rb
Labels: ARCH, FEAT
